-- 🦀 按按摩 - Supabase 数据库结构
-- 在 Supabase 后台 SQL Editor 里执行这段

-- ===== 网站设置 =====
CREATE TABLE site_config (
  id bigint PRIMARY KEY DEFAULT 1,
  site_name text NOT NULL DEFAULT '大马顶级会所，顶级水疗',
  tagline text NOT NULL DEFAULT '',
  whatsapp_number text NOT NULL DEFAULT '601114155848',
  telegram text NOT NULL DEFAULT '',
  areas text[] NOT NULL DEFAULT '{"吉隆坡","Cheras","Puchong","Kajang","Setapak","Subang","Petaling Jaya","Ampang"}',
  updated_at timestamptz DEFAULT now()
);

-- 禁止删掉配置行（只有一行，id=1）
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "所有人可读" ON site_config FOR SELECT USING (true);
CREATE POLICY "认证用户可改" ON site_config FOR ALL USING (true);

-- 插入默认配置
INSERT INTO site_config (id, site_name, tagline, whatsapp_number, telegram)
VALUES (1, '大马顶级会所，顶级水疗', '', '601114155848', '')
ON CONFLICT (id) DO NOTHING;

-- ===== 技师 =====
CREATE TABLE technicians (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL DEFAULT '',
  age int NOT NULL DEFAULT 25,
  area text NOT NULL DEFAULT '吉隆坡',
  cover_bg text NOT NULL DEFAULT 'linear-gradient(135deg, #667eea, #764ba2)',
  specialties text[] NOT NULL DEFAULT '{"按摩"}',
  rating numeric(2,1) NOT NULL DEFAULT 4.5,
  review_count int NOT NULL DEFAULT 0,
  price text NOT NULL DEFAULT 'RM 80/小时',
  phone text NOT NULL DEFAULT '',
  available boolean NOT NULL DEFAULT true,
  experience text NOT NULL DEFAULT '',
  height text NOT NULL DEFAULT '',
  weight text NOT NULL DEFAULT '',
  bust text NOT NULL DEFAULT '',
  origin text NOT NULL DEFAULT '',
  bio text NOT NULL DEFAULT '',
  service_range text NOT NULL DEFAULT '',
  photo_urls text[] NOT NULL DEFAULT '{}',
  video_url text NOT NULL DEFAULT '',
  services jsonb NOT NULL DEFAULT '[{"name":"按摩（1小时）","price":"RM 80"}]',
  reviews jsonb NOT NULL DEFAULT '[]',
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE technicians ENABLE ROW LEVEL SECURITY;
CREATE POLICY "所有人可读技师" ON technicians FOR SELECT USING (true);
CREATE POLICY "认证用户可改技师" ON technicians FOR ALL USING (true);

-- ===== 开启实时订阅 =====
-- 下面这行是说明，实际要在 Dashboard 操作：
-- Supabase 后台 → Database → Replication → 找到 site_config 和 technicians 表 → 开启 Realtime
